### ISSUE TITLE
app stop on searching

### ISSUE THREAD

**Issue by moslem7342** [synapticweb/CipherPass#2]

**Comment by synapticweb** [comment]
I'm not sure what you mean.

**Comment by moslem7342** [comment]
any search cause app crash

**Comment by synapticweb** [comment]
On what device are you running it? What android verdion?
Also please provide a logcat stacktrace of the crash.

**Comment by moslem7342** [comment]
sony-android-6
i find crash
app crash because TODO line in onQueryTextSubmit in EntriesListFragment
----

**Comment by moslem7342** [comment]
its better every time after write a letter in SearchView
make change on  main entry list 
 its simple by using setOnQueryTextListener
